set {
  # @Mod key
  $mod Mod4

  # @Apps
  $term kitty
  $menu rofi -show drun
  $browser zen-browser
  $file nautilus
  $music kitty --app-id jukebox -o window_padding_width=0 rmpc
  $clipboard-history bash $HOME/.config/sway/scripts/clipboard-history.sh
  
  # @Scripts
  $lock bash $HOME/.config/sway/scripts/lock.sh
  $logout bash $HOME/.config/sway/scripts/wlogout.sh
  $volume bash $HOME/.config/sway/scripts/volume.sh
  $media bash $HOME/.config/sway/scripts/media.sh
  $brightness bash $HOME/.config/sway/scripts/brightness.sh
  $screenshot bash $HOME/.config/sway/scripts/screenshot.sh
  $autostart bash $HOME/.config/sway/scripts/autostart.sh

  # @Home row direction
  $left h
  $down j
  $up k
  $right l

  # Colors ($bg-color, $accent-color...) and $radius come from the theme:
  # ~/.config/theme/current/sway.conf
}
