-- Generated by theme-gen.py from theme.toml (mode: day). Do not edit.
return {
	background = "light",
	palette = {
		base00 = "#EFE6D2",
		base01 = "#E6DAC0",
		base02 = "#DCCDAA",
		base03 = "#716349",
		base04 = "#4A3F2E",
		base05 = "#2A2218",
		base06 = "#1F190F",
		base07 = "#14100A",
		base08 = "#8A2929",
		base09 = "#855423",
		base0A = "#61470E",
		base0B = "#46501F",
		base0C = "#345046",
		base0D = "#304693",
		base0E = "#713B4D",
		base0F = "#6D4020",
	},
}
