#!/usr/bin/env python3
"""Render theme.toml into ~/.config/theme/{night,day}/
usage: theme-gen.py [--check]   --check only verifies contrast and writes nothing
"""

import pathlib
import sys

import tomllib

SRC = pathlib.Path(__file__).with_name("theme.toml")
OUT = pathlib.Path.home() / ".config" / "theme"
ROLES = [
    "bg",
    "bg_alt",
    "selection",
    "border",
    "fg",
    "fg_dim",
    "accent",
    "accent_2",
    "error",
]


# ---------- color helpers ----------
def rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i : i + 2], 16) for i in (0, 2, 4))


def hx(t):
    return "#{:02X}{:02X}{:02X}".format(*tuple(max(0, min(255, round(x))) for x in t))


def mix(a, b, t):
    ra, rb = rgb(a), rgb(b)
    return hx(tuple(ra[i] * (1 - t) + rb[i] * t for i in range(3)))


def rgba(h, a):
    r, g, b = rgb(h)
    return f"rgba({r}, {g}, {b}, {a})"


def hex8(h, a):
    return h.upper() + f"{round(a * 255):02X}"


def raw(h, a=None):
    s = h.lstrip("#").upper()
    return s + (f"{round(a * 255):02X}" if a is not None else "")


def _lin(c):
    c /= 255
    return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4


def lum(h):
    r, g, b = rgb(h)
    return 0.2126 * _lin(r) + 0.7152 * _lin(g) + 0.0722 * _lin(b)


def contrast(a, b):
    la, lb = sorted((lum(a), lum(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


# ---------- contrast gate  ----------
def check(name, m):
    bad = []
    for k, need in [
        ("fg", 7),
        ("fg_dim", 4.5),
        ("accent", 4.5),
        ("accent_2", 4.5),
        ("error", 4.5),
    ]:
        for bg in ("bg", "bg_alt"):
            r = contrast(m[k], m[bg])
            if r < need:
                bad.append(f"{name}: {k}/{bg} {r:.2f} < {need}")
    if contrast(m["fg"], m["selection"]) < 4.5:
        bad.append(f"{name}: fg/selection < 4.5")
    for i, c in enumerate(m["ansi"]):
        if i and contrast(c, m["bg"]) < 4.5:
            bad.append(f"{name}: ansi {i} {c} on bg {contrast(c, m['bg']):.2f} < 4.5")
    return bad


# ---------- renderers ----------
def derived(m):
    light = m["background"] == "light"
    hi = "#FFFFFF" if light else m["fg"]
    d = dict(m)
    d["light"] = light
    d["island_hi"] = mix(m["bg_alt"], hi, 0.35 if light else 0.06)
    d["inner_light"] = rgba(hi, 0.55 if light else 0.10)
    return d


def css_colors(m, scrim):
    d = derived(m)
    L = [f"@define-color {k} {m[k]};" for k in ROLES]
    L += [
        f"@define-color bg_glass {rgba(m['bg'], 0.86)};",
        f"@define-color island_hi {rgba(d['island_hi'], 0.90)};",
        f"@define-color island_lo {rgba(m['bg_alt'], 0.90)};",
        f"@define-color inner_light {d['inner_light']};",
        f"@define-color accent_soft {rgba(m['accent'], 0.18)};",
        f"@define-color accent_line {rgba(m['accent'], 0.55)};",
        f"@define-color hover {rgba(m['selection'], 0.95)};",
        f"@define-color scrim {rgba(m['bg'], scrim)};",
        # state glow: visible at night; in day the border color carries the state instead
        f"@define-color glow {rgba(m['accent'], 0.0 if d['light'] else 0.35)};",
        f"@define-color shadow {rgba('#000000', 0.35)};",
    ]
    return "\n".join(L) + "\n"


def render(mode, m, s, night):
    derived(m)
    hdr = f"Generated by theme-gen.py from theme.toml (mode: {mode}). Do not edit."
    files = {}

    # sway
    sway = [f"# {hdr}", "set {"]
    sway += [
        f"  $bg-color            {m['bg']}",
        f"  $text-color          {m['fg']}",
        f"  $inactive-text-color {m['fg_dim']}",
        f"  $urgent-bg-color     {m['error']}",
        f"  $accent-color        {m['accent']}",
        f"  $overlay-bg-color    {m['selection']}",
        f"  $radius              {s['radius']}",
        "}",
        f"corner_radius {s['radius']}",
        f"shadow_color {hex8('#000000', 0.40)}",
        "gaps {",
        f"  inner {s['gaps_inner']}px",
        f"  outer {s['gaps_outer']}px",
        "}",
        # the block above is only the default of NEW workspaces: sway does not touch the
        # existing ones on reload. `all set` is a live command (not valid in a config file),
        # so it runs after every reload. Edge margin = inner + outer.
        f'exec_always swaymsg "gaps inner all set {s["gaps_inner"]}; gaps outer all set {s["gaps_outer"]}"',
    ]
    files["sway.conf"] = "\n".join(sway) + "\n"
    if m["wallpaper"]:
        wp = f"output * bg {m['wallpaper']} fill"
    else:
        wp = f"output * bg {m['bg']} solid_color"
    files["sway-wallpaper.conf"] = f"# {hdr}\n{wp}\n"

    # kitty
    k = [
        f"# {hdr}",
        f'font_family      family="{s["font_mono"]}"',
        f"font_size        {s['kitty_size']}",
        f"window_padding_width {s['kitty_padding']}",
        f"background_opacity {s['kitty_opacity']}",
        f"background            {m['bg']}",
        f"foreground            {m['fg']}",
        f"selection_background  {m['selection']}",
        f"selection_foreground  {m['fg']}",
        f"cursor                {m['accent']}",
        f"cursor_text_color     {m['bg']}",
        f"url_color             {m['accent_2']}",
    ]
    k += [f"color{i:<2d} {c}" for i, c in enumerate(m["ansi"])]
    files["kitty.conf"] = "\n".join(k) + "\n"

    # GTK css (waybar, wlogout: GTK3; swaync: GTK4) share the same named colors
    css = f"/* {hdr} */\n" + css_colors(m, s["scrim_opacity"])
    files["waybar.css"] = css
    files["wlogout.css"] = css
    files["swaync.css"] = css

    # rofi
    r = [f"/* {hdr} */", "* {"]
    r += [f"  {k.replace('_', '-')}: {hex8(m[k], 1)};" for k in ROLES]
    r += [
        f"  scrim: {hex8(m['bg'], s['scrim_opacity'])};",
        f"  bg-glass: {hex8(m['bg'], 0.96)};",
        f"  accent-soft: {hex8(m['accent'], 0.18)};",
        f"  radius: {s['radius']}px;",
        f'  ui-font: "{s["font_ui"]} {s["ui_pt"]}";',
        "}",
    ]
    files["rofi.rasi"] = "\n".join(r) + "\n"

    # swaylock-effects
    n = night
    clear = "00000000"
    sl = [
        f"# {hdr}",
        "# (night colors in both modes: the background is darkened whatever the mode)",
        f"font={s['font_ui']}",
        f"text-color={raw(n['fg'])}",
        f"text-clear-color={raw(n['fg_dim'])}",
        f"text-ver-color={raw(n['accent_2'])}",
        f"text-wrong-color={raw(n['error'])}",
        f"text-caps-lock-color={raw(n['accent'])}",
        f"key-hl-color={raw(n['accent'], 0.93)}",
        f"bs-hl-color={raw(n['error'])}",
        f"caps-lock-key-hl-color={raw(n['accent'])}",
        f"caps-lock-bs-hl-color={raw(n['error'])}",
        f"ring-color={clear}",
        f"ring-ver-color={raw(n['accent_2'], 0.80)}",
        f"ring-wrong-color={raw(n['error'], 0.80)}",
        f"ring-clear-color={raw(n['fg_dim'], 0.60)}",
        f"ring-caps-lock-color={clear}",
        f"line-color={clear}",
        f"line-ver-color={clear}",
        f"line-wrong-color={clear}",
        f"line-clear-color={clear}",
        f"line-caps-lock-color={clear}",
        f"inside-color={clear}",
        f"inside-ver-color={clear}",
        f"inside-wrong-color={clear}",
        f"inside-clear-color={clear}",
        f"inside-caps-lock-color={clear}",
        f"separator-color={clear}",
    ]
    files["swaylock.conf"] = "\n".join(sl) + "\n"

    # nvim (mini.base16)
    b = [
        f"-- {hdr}",
        "return {",
        f'\tbackground = "{m["background"]}",',
        "\tpalette = {",
    ]
    b += [f'\t\tbase{i:02X} = "{c}",' for i, c in enumerate(m["base16"])]
    b += ["\t},", "}"]
    files["nvim.lua"] = "\n".join(b) + "\n"
    return files


def wlogout_labels(layout_path):
    """layout is a stream of JSON objects: {"label": "lock", "text": "Bloquear", ...}"""
    import json

    text = pathlib.Path(layout_path).expanduser().read_text()
    dec, i, out = json.JSONDecoder(), 0, {}
    while i < len(text):
        if text[i].isspace():
            i += 1
            continue
        obj, i = dec.raw_decode(text, i)
        out[obj["label"]] = obj.get("text", obj["label"])
    return out


def tint_icons(mode, m, s):
    """wlogout tiles: icon + label drawn together in one image, so they stay centered and
    close to each other whatever the size of the (stretched) button is. Normal tile in fg;
    "-active" tile (the one under the pointer) in accent, with an underline."""
    try:
        import subprocess

        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        print("  (sin Pillow: los iconos de wlogout no se generan)")
        return 0
    font_file = subprocess.run(
        ["fc-match", "-f", "%{file}", f"{s['font_ui']}:weight=medium"],
        check=False,
        capture_output=True,
        text=True,
    ).stdout
    S = 2  # supersampling: the tile is drawn at 2x and displayed at 1x (see wlogout/style.css)
    icon_px, label_px = s["icon_px"] * S, s["label_px"] * S
    W, H = 200 * S, 150 * S
    font = ImageFont.truetype(font_file, label_px)
    labels = wlogout_labels(s["layout_file"])
    src = pathlib.Path(s["icons_src"]).expanduser()
    dst = OUT / mode / "wlogout"
    dst.mkdir(parents=True, exist_ok=True)
    n = 0
    for f in sorted(src.glob("*.png")):
        label = labels.get(f.stem, f.stem)
        alpha = (
            Image.open(f)
            .convert("RGBA")
            .split()[3]
            .resize((icon_px,) * 2, Image.LANCZOS)
        )
        for suffix, color in (("", m["fg"]), ("-active", m["accent"])):
            tile = Image.new("RGBA", (W, H), (0, 0, 0, 0))
            icon = Image.new("RGBA", alpha.size, rgb(color) + (255,))
            icon.putalpha(alpha)
            top = 24 * S
            tile.paste(icon, ((W - icon_px) // 2, top), icon)
            d = ImageDraw.Draw(tile)
            ty = top + icon_px + 18 * S
            d.text(
                (W // 2, ty), label, font=font, fill=rgb(color) + (255,), anchor="mt"
            )
            if suffix:  # underline only on the current one
                half = d.textlength(label, font=font) / 2 + 14 * S
                uy = ty + label_px + 10 * S
                d.rectangle(
                    [W // 2 - half, uy, W // 2 + half, uy + 2 * S],
                    fill=rgb(color) + (255,),
                )
            tile.save(dst / f"{f.stem}{suffix}.png")
            n += 1
    return n


def main():
    with SRC.open("rb") as f:
        data = tomllib.load(f)
    s = data["shared"]
    problems = []
    for mode in ("night", "day"):
        problems += check(mode, data[mode])
        assert len(data[mode]["ansi"]) == 16 and len(data[mode]["base16"]) == 16, mode
    if problems:
        print("CONTRASTE INSUFICIENTE, no se escribe nada:\n  " + "\n  ".join(problems))
        sys.exit(1)
    print("contraste ok (noche y dia)")
    if "--check" in sys.argv:
        return
    for mode in ("night", "day"):
        d = OUT / mode
        d.mkdir(parents=True, exist_ok=True)
        for name, text in render(mode, data[mode], s, data["night"]).items():
            (d / name).write_text(text)
        print(
            f"  {d}: {len(render(mode, data[mode], s, data['night']))} archivos + {tint_icons(mode, data[mode], s)} iconos"
        )
    cur = OUT / "current"
    if not cur.exists() and not cur.is_symlink():
        cur.symlink_to("night")
        print("  current -> night (creado)")


if __name__ == "__main__":
    main()
