font_family      family="GeistMono Nerd Font Mono"
font_size        10.5
window_padding_width 4
background_opacity 0.93
background            #181616
foreground            #D4BE98
selection_background  #2E2A2A
selection_foreground  #D4BE98
cursor                #C87941
cursor_text_color     #181616
url_color             #689D8A
color0  #181616
color1  #D26464
color2  #B4C76E
color3  #E7BB5C
color4  #7B8FD4
color5  #B57188
color6  #689D8A
color7  #C2C2C2
color8  #928374
color9  #E67B7B
color10 #CAD98A
color11 #F0CC7A
color12 #9AAAE0
color13 #C8889A
color14 #89B8A8
color15 #D4BE98
