font=GeistMono Nerd Font Propo
text-color=D4BE98
text-caps-lock-color=D4BE98
ring-color=C87941AB
ring-ver-color=689D8ACC
ring-wrong-color=D26464CC
ring-clear-color=689D8ABA
key-hl-color=C87941ED
bs-hl-color=D26464
line-color=18161633
inside-color=18161654
inside-ver-color=689D8A33
inside-wrong-color=D2646433
inside-clear-color=C8794121
separator-color=00000000
