set {
  $bg-color            #181616
  $text-color          #D4BE98
  $inactive-text-color #928374
  $urgent-bg-color     #D26464
  $accent-color        #C87941
  $overlay-bg-color    #2E2A2A
  $radius              10
}
corner_radius 10
shadow_color #00000066
gaps {
  inner 8px
  outer 16px
}
exec_always swaymsg "gaps inner all set 8; gaps outer all set 16"
